protos:
  - '**.protos'
  
rust:
  - '**.rs'
  - '**/Cargo.lock'
  - '**/Cargo.toml'

dependencies:
  - '**/buf.lock'
  - '**/Cargo.lock'

github_actions:
  - '.github/workflows/**'
  - '.github/labeler.yaml'
  - '.github/triage-labeler.yaml'
